### ISSUE TITLE
Steam Group problem!

### ISSUE THREAD

**Issue by Cripix** [yash1441/SteamInviter#1]
Hi !
I tried to use your plugin but I can not get the main function function (invites steam group) and I have this error:
"Server is busy with another task at this time, try again in a few seconds"
But the automatic add of friends works very well.
How can I solve it?

And I will be a cvar to disable the automatic add of friends ?

Thanks !

**Comment by yash1441** [comment]
Recently Steam pushed an update [[Read Here](http://steamcommunity.com/games/593110/announcements/detail/1446071197008661976)] and now onwards you can't invite anyone without being friends first.
So the plugin first adds as friend and until the player accepts it can't invite to group.

_"Server is busy with another task at this time, try again in a few seconds"
"cvar to disable the automatic add of friends "_

I updated the plugin, added cvars as well.

**Comment by Cripix** [comment]
No work :(

============================================================================

Logging in to keep login alive...

============================================================================

Obtaining RSA Key from steamcommunity.com/login/getrsakey...
Steam Core is busy, couldn't invite to group.
{"success":true,"publickey_mod":"ec6eec9e8ee9078ce290894bd157c4771bced0db5f9f201a9a0084b652f33222c73dfd82d97646d2d1055c338f1b5b5a3760112b20398082a90d50035b9c440bc68c79392f3431397fbc7439d9bf5467b1266c85855b47db8e651dee01d03047d6a1124089cbcea839530b75c96331477bae175ea66cdb1e66851e1cada17b182cb2bfe915c1771f34cf7fcec483923443a64e64bc409d115d7fd58619c8214e20e8b45afb592dc5364b7caa6c72aa5d14f98c86369bc71c34a93134ab8200a7c379aa01a6e80fdf9736b034e4f8dcf3e98a55951c206d01db8d654be446aeb473da88272df66215f3c3666b98da97cd0a92a4ffe1d4917adcee99def5f8da4f","publickey_exp":"010001","timestamp":"1004763450000","token_gid":"128d7aab5de4b1e8"}
RSA KEY MODULUS (512): 
ec6eec9e8ee9078ce290894bd157c4771bced0db5f9f201a9a0084b652f33222c73dfd82d97646d2d1055c338f1b5b5a3760112b20398082a90d50035b9c440bc68c79392f3431397fbc7439d9bf5467b1266c85855b47db8e651dee01d03047d6a1124089cbcea839530b75c96331477bae175ea66cdb1e66851e1cada17b182cb2bfe915c1771f34cf7fcec483923443a64e64bc409d115d7fd58619c8214e20e8b45afb592dc5364b7caa6c72aa5d14f98c86369bc71c34a93134ab8200a7c379aa01a6e80fdf9736b034e4f8dcf3e98a55951c206d01db8d654be446aeb473da88272df66215f3c3666b98da97cd0a92a4ffe1d4917adcee99def5f8da4f
RSA KEY EXPONENT (6): 010001
STEAM TIMESTAMP (13): 1004763450000

============================================================================

Encrypting passphrase ******** with RSA public key...
Padded message with PKCS#1 v1.5 standard (512): 
0002DF995AE26BEEE9B7B9CEEBE9ACDBA09435A7BE97CE76287C57829AB0FEF1FF37CE27756D9E48BEB52C73DA90DD523A2FE9833835F1BBEECB4DFEE31B4E3927308AD852623447E299DA1BBE6CAFA0D7F2E99E691A22DF44161282DDF08DE4F727BFA0A15F719644574B7C65ECD957678C98D14A98B233872EAA9E313F93FA14AC3C9446F0DD62CAC7FC6C5F396C181597A2E0823234F97F62A8C33B8D6A489BB8B47A1332134E37D6E3FA8B1017BE23639956BBAC6783132379F2ECBB154E7B9199D52CEB376EBCD0769F4A59

**Comment by yash1441** [comment]
**1.** Is the client added as friend to the bot account?
**2.** Try commenting out https://github.com/yash1441/SteamInviter/blob/master/csgo/addons/sourcemod/scripting/SteamInviter.sp#L52-L56 then compile and test.

**Comment by Cripix** [comment]
1.Yes

2.With the modif version=

============================================================================

Logging in to keep login alive...

============================================================================

Obtaining RSA Key from steamcommunity.com/login/getrsakey...

And I have no more

**Comment by yash1441** [comment]
Another user of my plugin had this issue where people weren't invited to group.
Can you open up an issue [here](https://github.com/polvora/SteamCore/issues)? You can post link to this plugin's source and the log that you got without the commenting part or just mention link to this issue. Should be a problem with Steam Core if I'm not wrong.

**Comment by Cripix** [comment]
https://github.com/polvora/SteamCore/issues/11

^^

**Comment by Cripix** [comment]
It's really weird because it worked for 30 minutes then now I have the error 0x26.

**Comment by yash1441** [comment]
https://github.com/polvora/SteamCore/issues/6 Check this out.

**Comment by Cripix** [comment]
Hi !

With the latest version of streamcore I now have this error:
SteamInviter.smx (Steam Inviter): Native "IsSteamCoreBusy" was not found

Can you solve it?

Thanks !

**Comment by yash1441** [comment]
Updating with the new code.

**Comment by Cripix** [comment]
Yes I have already done the update

**Comment by yash1441** [comment]
https://github.com/yash1441/SteamInviter/releases/tag/1.6

Tell me if it works!

**Comment by Cripix** [comment]
I have installed this version

But I have no log or invitation ???

**Comment by yash1441** [comment]
Did you login to the steam account using the new convars of steamcore?

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Cripix** [comment]
Yes I have configured with the new method

**Comment by yash1441** [comment]
Confirmed by 2 people, Steam Group Invite function works. Closing this for now, if you still have a problem then feel free to reopen this issue or create a new one.
